-- GENERATED by tools/make_lean.py from spec/antikythera.json. Do not edit by hand.

import Mathlib

/-!
# The Antikythera Mechanism: kinematics of the gearing

Every moving part is a `Body`. `ω x` is the MEAN rate of body `x` in turns per year about its own axis,
positive = clockwise seen from the front (spec `conventions.rate_sign`); `b` is the main wheel b1
(1 turn = 1 year). Two exceptions, both on perpendicular axes: `ω .a` is the crank's rate about the x axis,
counted positive when it drives b1 clockwise (spec `conventions.crank`), and `ω .q` is the Moon-phase
ball's rate RELATIVE TO THE MOON POINTER about its radial axis (spec `conventions.moon_phase`).
`Kinematics ω` collects one equation per gear contact, taken from the tooth counts of the spec.

Main results: `determined` and `determined_by_crank` (the crank fixes every mean rate), `consistent`
(the equations admit a solution for every crank speed: no over-constrained loop), `moves` (the
mechanism can turn: the hypotheses used elsewhere are satisfiable with b1 turning) and `one_dof` (the
admissible mean-rate vectors form exactly one line: one degree of freedom). These are statements about
MEAN rates; the nonlinear pin-and-slot and follower laws are treated in `Antikythera.PinSlot`, and
geometric interference (collisions) is outside the scope of the Lean proofs.
-/

namespace Antikythera

/-- The rigid bodies of the mechanism (spec `bodies`). -/
inductive Body where
  | frame -- fixed; gears fx51, fx49, fx56
  | a -- crank; gears a1 (rate about the x axis)
  | b -- revolute; gears b1, b2, b0
  | moon -- revolute; gears b3
  | c -- revolute; gears c2, c1
  | d -- revolute; gears d1, d2
  | e_pipe -- revolute; gears e2, e5
  | e_table -- revolute; gears e3, e4
  | e_inner -- pin_slot_driven; gears e1, e6
  | k -- revolute; gears k1
  | kp -- pin_slot_output; gears k2
  | l -- revolute; gears l2, l1
  | m -- revolute; gears m1, m3, m2
  | f -- revolute; gears f1, f2
  | g -- revolute; gears g1, g2
  | h -- revolute; gears h1, h2
  | i -- revolute; gears i1
  | n -- revolute; gears n1, n3, n2
  | o -- revolute; gears o1
  | p -- revolute; gears p1, p2
  | cal -- revolute; gears cal1
  | q -- nonlinear_crown; gears q1 (rate relative to the Moon pointer, radial axis)
  | spA -- revolute; gears me72, me89
  | spB -- revolute; gears nd62, nd64
  | spC -- revolute; gears vn44, vn34
  | x_me40 -- revolute; gears me40
  | x_me20 -- revolute; gears me20
  | x_vn26 -- revolute; gears vn26
  | x_r1 -- revolute; gears r1
  | t_nodes -- revolute; gears nd48
  | x_cp52 -- revolute; gears cp52, sa61
  | x_cp64 -- revolute; gears cp64, ma38, ju45
  | x_su56 -- revolute; gears su56
  | x_sa40 -- revolute; gears sa40
  | x_sa68 -- revolute; gears sa68
  | x_sa86s -- pin_slot_output; gears sa86s
  | x_ju40 -- revolute; gears ju40
  | x_ju43 -- revolute; gears ju43
  | x_ju65s -- pin_slot_output; gears ju65s
  | x_ma40 -- revolute; gears ma40
  | x_ma71 -- revolute; gears ma71
  | x_ma80s -- pin_slot_output; gears ma80s
  | t_saturn -- pin_slot_driven; gears sa86o
  | t_jupiter -- pin_slot_driven; gears ju65o
  | t_mars -- pin_slot_driven; gears ma80o
  | t_mercury -- follower; gears —
  | t_venus -- follower; gears —
  | t_trueSun -- follower; gears —
  deriving DecidableEq, Repr

/-- The gear-contact constraints on the mean rates `ω`. -/
structure Kinematics (ω : Body → ℝ) : Prop where
  /-- The frame (plates, fixed central tube, Sub-Plate gear) does not turn. -/
  frame_fixed : ω .frame = 0
  /-- b2 (64 teeth, on `b`) meshes with c1 (38 teeth, on `c`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_b2_c1 : 64 * (ω .b - ω .frame) + 38 * (ω .c - ω .frame) = 0
  /-- c2 (48 teeth, on `c`) meshes with d1 (24 teeth, on `d`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_c2_d1 : 48 * (ω .c - ω .frame) + 24 * (ω .d - ω .frame) = 0
  /-- d2 (127 teeth, on `d`) meshes with e2 (32 teeth, on `e_pipe`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_d2_e2 : 127 * (ω .d - ω .frame) + 32 * (ω .e_pipe - ω .frame) = 0
  /-- b2 (64 teeth, on `b`) meshes with l1 (38 teeth, on `l`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_b2_l1 : 64 * (ω .b - ω .frame) + 38 * (ω .l - ω .frame) = 0
  /-- l2 (53 teeth, on `l`) meshes with m1 (96 teeth, on `m`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_l2_m1 : 53 * (ω .l - ω .frame) + 96 * (ω .m - ω .frame) = 0
  /-- m3 (27 teeth, on `m`) meshes with e3 (223 teeth, on `e_table`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_m3_e3 : 27 * (ω .m - ω .frame) + 223 * (ω .e_table - ω .frame) = 0
  /-- e5 (50 teeth, on `e_pipe`) meshes with k1 (50 teeth, on `k`); axes carried by `e_table`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_e5_k1 : 50 * (ω .e_pipe - ω .e_table) + 50 * (ω .k - ω .e_table) = 0
  /-- k2 (50 teeth, on `kp`) meshes with e6 (50 teeth, on `e_inner`); axes carried by `e_table`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_k2_e6 : 50 * (ω .kp - ω .e_table) + 50 * (ω .e_inner - ω .e_table) = 0
  /-- e1 (32 teeth, on `e_inner`) meshes with b3 (32 teeth, on `moon`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_e1_b3 : 32 * (ω .e_inner - ω .frame) + 32 * (ω .moon - ω .frame) = 0
  /-- e4 (188 teeth, on `e_table`) meshes with f1 (53 teeth, on `f`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_e4_f1 : 188 * (ω .e_table - ω .frame) + 53 * (ω .f - ω .frame) = 0
  /-- f2 (30 teeth, on `f`) meshes with g1 (54 teeth, on `g`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_f2_g1 : 30 * (ω .f - ω .frame) + 54 * (ω .g - ω .frame) = 0
  /-- g2 (20 teeth, on `g`) meshes with h1 (60 teeth, on `h`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_g2_h1 : 20 * (ω .g - ω .frame) + 60 * (ω .h - ω .frame) = 0
  /-- h2 (15 teeth, on `h`) meshes with i1 (60 teeth, on `i`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_h2_i1 : 15 * (ω .h - ω .frame) + 60 * (ω .i - ω .frame) = 0
  /-- m2 (15 teeth, on `m`) meshes with n1 (53 teeth, on `n`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_m2_n1 : 15 * (ω .m - ω .frame) + 53 * (ω .n - ω .frame) = 0
  /-- n3 (57 teeth, on `n`) meshes with o1 (60 teeth, on `o`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_n3_o1 : 57 * (ω .n - ω .frame) + 60 * (ω .o - ω .frame) = 0
  /-- n2 (15 teeth, on `n`) meshes with p1 (60 teeth, on `p`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_n2_p1 : 15 * (ω .n - ω .frame) + 60 * (ω .p - ω .frame) = 0
  /-- p2 (12 teeth, on `p`) meshes with cal1 (60 teeth, on `cal`); axes carried by `frame`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_p2_cal1 : 12 * (ω .p - ω .frame) + 60 * (ω .cal - ω .frame) = 0
  /-- fx49 (49 teeth, on `frame`) meshes with nd62 (62 teeth, on `spB`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_fx49_nd62 : 49 * (ω .frame - ω .b) + 62 * (ω .spB - ω .b) = 0
  /-- nd64 (64 teeth, on `spB`) meshes with nd48 (48 teeth, on `t_nodes`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_nd64_nd48 : 64 * (ω .spB - ω .b) + 48 * (ω .t_nodes - ω .b) = 0
  /-- fx51 (51 teeth, on `frame`) meshes with vn44 (44 teeth, on `spC`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_fx51_vn44 : 51 * (ω .frame - ω .b) + 44 * (ω .spC - ω .b) = 0
  /-- vn34 (34 teeth, on `spC`) meshes with vn26 (26 teeth, on `x_vn26`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_vn34_vn26 : 34 * (ω .spC - ω .b) + 26 * (ω .x_vn26 - ω .b) = 0
  /-- vn26 (26 teeth, on `x_vn26`) meshes with r1 (63 teeth, on `x_r1`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_vn26_r1 : 26 * (ω .x_vn26 - ω .b) + 63 * (ω .x_r1 - ω .b) = 0
  /-- fx51 (51 teeth, on `frame`) meshes with me72 (72 teeth, on `spA`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_fx51_me72 : 51 * (ω .frame - ω .b) + 72 * (ω .spA - ω .b) = 0
  /-- me89 (89 teeth, on `spA`) meshes with me40 (40 teeth, on `x_me40`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_me89_me40 : 89 * (ω .spA - ω .b) + 40 * (ω .x_me40 - ω .b) = 0
  /-- me40 (40 teeth, on `x_me40`) meshes with me20 (20 teeth, on `x_me20`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_me40_me20 : 40 * (ω .x_me40 - ω .b) + 20 * (ω .x_me20 - ω .b) = 0
  /-- fx56 (56 teeth, on `frame`) meshes with cp52 (52 teeth, on `x_cp52`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_fx56_cp52 : 56 * (ω .frame - ω .b) + 52 * (ω .x_cp52 - ω .b) = 0
  /-- cp52 (52 teeth, on `x_cp52`) meshes with su56 (56 teeth, on `x_su56`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_cp52_su56 : 52 * (ω .x_cp52 - ω .b) + 56 * (ω .x_su56 - ω .b) = 0
  /-- fx56 (56 teeth, on `frame`) meshes with cp64 (64 teeth, on `x_cp64`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_fx56_cp64 : 56 * (ω .frame - ω .b) + 64 * (ω .x_cp64 - ω .b) = 0
  /-- sa61 (61 teeth, on `x_cp52`) meshes with sa40 (40 teeth, on `x_sa40`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_sa61_sa40 : 61 * (ω .x_cp52 - ω .b) + 40 * (ω .x_sa40 - ω .b) = 0
  /-- sa40 (40 teeth, on `x_sa40`) meshes with sa68 (68 teeth, on `x_sa68`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_sa40_sa68 : 40 * (ω .x_sa40 - ω .b) + 68 * (ω .x_sa68 - ω .b) = 0
  /-- sa86s (86 teeth, on `x_sa86s`) meshes with sa86o (86 teeth, on `t_saturn`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_sa86s_sa86o : 86 * (ω .x_sa86s - ω .b) + 86 * (ω .t_saturn - ω .b) = 0
  /-- ju45 (45 teeth, on `x_cp64`) meshes with ju40 (40 teeth, on `x_ju40`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_ju45_ju40 : 45 * (ω .x_cp64 - ω .b) + 40 * (ω .x_ju40 - ω .b) = 0
  /-- ju40 (40 teeth, on `x_ju40`) meshes with ju43 (43 teeth, on `x_ju43`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_ju40_ju43 : 40 * (ω .x_ju40 - ω .b) + 43 * (ω .x_ju43 - ω .b) = 0
  /-- ju65s (65 teeth, on `x_ju65s`) meshes with ju65o (65 teeth, on `t_jupiter`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_ju65s_ju65o : 65 * (ω .x_ju65s - ω .b) + 65 * (ω .t_jupiter - ω .b) = 0
  /-- ma38 (38 teeth, on `x_cp64`) meshes with ma40 (40 teeth, on `x_ma40`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_ma38_ma40 : 38 * (ω .x_cp64 - ω .b) + 40 * (ω .x_ma40 - ω .b) = 0
  /-- ma40 (40 teeth, on `x_ma40`) meshes with ma71 (71 teeth, on `x_ma71`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_ma40_ma71 : 40 * (ω .x_ma40 - ω .b) + 71 * (ω .x_ma71 - ω .b) = 0
  /-- ma80s (80 teeth, on `x_ma80s`) meshes with ma80o (80 teeth, on `t_mars`); axes carried by `b`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0. -/
  mesh_ma80s_ma80o : 80 * (ω .x_ma80s - ω .b) + 80 * (ω .t_mars - ω .b) = 0
  /-- Crown (contrate) pair a1 (48) → b1 (223) on perpendicular axes: the crank `a` turns 223/48 times per turn of b1 (sense of `a` counted positive when it drives b1 clockwise). -/
  crown_a1_b1 : 48 * ω .a = 223 * ω .b
  /-- Crown pair b0 (20, on `b`) → q1 (20, the Moon-phase ball `q`) on the Moon pointer. `ω .q` is the ball's rate RELATIVE TO THE MOON POINTER about its radial axis, right-handed (spec `conventions.moon_phase`: θ_q = θ_b − θ_moon in counterclockwise world angles, i.e. ω_q = ω_moon − ω_b in the clockwise-positive rates used here): one turn per synodic month. -/
  crown_b0_q1 : 20 * ω .q = 20 * (ω .moon - ω .b)
  /-- Pin-and-slot `lunar` (k1 → k2, pin radius 9.6 mm, offset 1.1 mm): the slot gear's MEAN rate equals the pin gear's (the angular lag is bounded, see `Antikythera.PinSlot.kinematics_nonlinear_fields`, which derives this equation from the spec's nonlinear law). -/
  pinslot_lunar : ω .kp = ω .k
  /-- Pin-and-slot `saturn` (sa68 → sa86s, pin radius 14.37 mm, offset 1.5 mm): the slot gear's MEAN rate equals the pin gear's (the angular lag is bounded, see `Antikythera.PinSlot.kinematics_nonlinear_fields`, which derives this equation from the spec's nonlinear law). -/
  pinslot_saturn : ω .x_sa86s = ω .x_sa68
  /-- Pin-and-slot `jupiter` (ju43 → ju65s, pin radius 8.22 mm, offset 1.58 mm): the slot gear's MEAN rate equals the pin gear's (the angular lag is bounded, see `Antikythera.PinSlot.kinematics_nonlinear_fields`, which derives this equation from the spec's nonlinear law). -/
  pinslot_jupiter : ω .x_ju65s = ω .x_ju43
  /-- Pin-and-slot `mars` (ma71 → ma80s, pin radius 10.0 mm, offset 6.58 mm): the slot gear's MEAN rate equals the pin gear's (the angular lag is bounded, see `Antikythera.PinSlot.kinematics_nonlinear_fields`, which derives this equation from the spec's nonlinear law). -/
  pinslot_mars : ω .x_ma80s = ω .x_ma71
  /-- Follower `mercury` (pin on `x_me20`, i = 36.0, d = 14.04): its MEAN rate is the Sun's (the lag is bounded because d < i, see `Antikythera.PinSlot.kinematics_nonlinear_fields`). -/
  follower_mercury : ω .t_mercury = ω .b
  /-- Follower `venus` (pin on `x_r1`, i = 27.8, d = 20.01): its MEAN rate is the Sun's (the lag is bounded because d < i, see `Antikythera.PinSlot.kinematics_nonlinear_fields`). -/
  follower_venus : ω .t_venus = ω .b
  /-- Follower `trueSun` (pin on `x_su56`, i = 39.711744, d = 1.654656): its MEAN rate is the Sun's (the lag is bounded because d < i, see `Antikythera.PinSlot.kinematics_nonlinear_fields`). -/
  follower_trueSun : ω .t_trueSun = ω .b

/-- The mean rates for b1 = 1 turn per year, computed exactly from the tooth counts. -/
noncomputable def rate : Body → ℝ
  | .frame => 0
  | .a => 223 / 48
  | .b => 1
  | .moon => 254 / 19
  | .c => -32 / 19
  | .d => 64 / 19
  | .e_pipe => -254 / 19
  | .e_table => -477 / 4237
  | .e_inner => -254 / 19
  | .k => 55688 / 4237
  | .kp => 55688 / 4237
  | .l => -32 / 19
  | .m => 53 / 57
  | .f => 1692 / 4237
  | .g => -940 / 4237
  | .h => 940 / 12711
  | .i => -235 / 12711
  | .n => -5 / 19
  | .o => 1 / 4
  | .p => 5 / 76
  | .cal => -1 / 76
  | .q => 235 / 19
  | .spA => 41 / 24
  | .spB => 111 / 62
  | .spC => 95 / 44
  | .x_me40 => -553 / 960
  | .x_me20 => 1993 / 480
  | .x_vn26 => -295 / 572
  | .x_r1 => 751 / 462
  | .t_nodes => -5 / 93
  | .x_cp52 => 27 / 13
  | .x_cp64 => 15 / 8
  | .x_su56 => 0
  | .x_sa40 => -167 / 260
  | .x_sa68 => 869 / 442
  | .x_sa86s => 869 / 442
  | .x_ju40 => 1 / 64
  | .x_ju43 => 659 / 344
  | .x_ju65s => 659 / 344
  | .x_ma40 => 27 / 160
  | .x_ma71 => 417 / 284
  | .x_ma80s => 417 / 284
  | .t_saturn => 15 / 442
  | .t_jupiter => 29 / 344
  | .t_mars => 151 / 284
  | .t_mercury => 1
  | .t_venus => 1
  | .t_trueSun => 1

/-- **Consistency**: for every crank speed `t` the rates `t • rate` satisfy all constraints: the
47 equations are independent (48 bodies, no over-constrained loop). -/
theorem consistent (t : ℝ) : Kinematics (fun x => t * rate x) := by
  constructor <;> simp only [rate] <;> ring

/-- **Determinism**: any rates satisfying the constraints are fixed by the rate of b1. -/
theorem determined (ω : Body → ℝ) (h : Kinematics ω) : ∀ x, ω x = ω .b * rate x := by
  have h_b : ω .b = ω .b * 1 := by ring
  have h_frame : ω .frame = ω .b * (0) := by
    linear_combination (1 : ℝ) * h.frame_fixed
  have h_c : ω .c = ω .b * (-32 / 19) := by
    linear_combination (1 / 38 : ℝ) * h.mesh_b2_c1 + (-32 / 19 : ℝ) * h_b + (51 / 19 : ℝ) * h_frame
  have h_d : ω .d = ω .b * (64 / 19) := by
    linear_combination (1 / 24 : ℝ) * h.mesh_c2_d1 + (-2 : ℝ) * h_c + (3 : ℝ) * h_frame
  have h_e_pipe : ω .e_pipe = ω .b * (-254 / 19) := by
    linear_combination (1 / 32 : ℝ) * h.mesh_d2_e2 + (-127 / 32 : ℝ) * h_d + (159 / 32 : ℝ) * h_frame
  have h_l : ω .l = ω .b * (-32 / 19) := by
    linear_combination (1 / 38 : ℝ) * h.mesh_b2_l1 + (-32 / 19 : ℝ) * h_b + (51 / 19 : ℝ) * h_frame
  have h_m : ω .m = ω .b * (53 / 57) := by
    linear_combination (1 / 96 : ℝ) * h.mesh_l2_m1 + (-53 / 96 : ℝ) * h_l + (149 / 96 : ℝ) * h_frame
  have h_e_table : ω .e_table = ω .b * (-477 / 4237) := by
    linear_combination (1 / 223 : ℝ) * h.mesh_m3_e3 + (-27 / 223 : ℝ) * h_m + (250 / 223 : ℝ) * h_frame
  have h_k : ω .k = ω .b * (55688 / 4237) := by
    linear_combination (1 / 50 : ℝ) * h.mesh_e5_k1 + (-1 : ℝ) * h_e_pipe + (2 : ℝ) * h_e_table
  have h_f : ω .f = ω .b * (1692 / 4237) := by
    linear_combination (1 / 53 : ℝ) * h.mesh_e4_f1 + (-188 / 53 : ℝ) * h_e_table + (241 / 53 : ℝ) * h_frame
  have h_g : ω .g = ω .b * (-940 / 4237) := by
    linear_combination (1 / 54 : ℝ) * h.mesh_f2_g1 + (-5 / 9 : ℝ) * h_f + (14 / 9 : ℝ) * h_frame
  have h_h : ω .h = ω .b * (940 / 12711) := by
    linear_combination (1 / 60 : ℝ) * h.mesh_g2_h1 + (-1 / 3 : ℝ) * h_g + (4 / 3 : ℝ) * h_frame
  have h_i : ω .i = ω .b * (-235 / 12711) := by
    linear_combination (1 / 60 : ℝ) * h.mesh_h2_i1 + (-1 / 4 : ℝ) * h_h + (5 / 4 : ℝ) * h_frame
  have h_n : ω .n = ω .b * (-5 / 19) := by
    linear_combination (1 / 53 : ℝ) * h.mesh_m2_n1 + (-15 / 53 : ℝ) * h_m + (68 / 53 : ℝ) * h_frame
  have h_o : ω .o = ω .b * (1 / 4) := by
    linear_combination (1 / 60 : ℝ) * h.mesh_n3_o1 + (-19 / 20 : ℝ) * h_n + (39 / 20 : ℝ) * h_frame
  have h_p : ω .p = ω .b * (5 / 76) := by
    linear_combination (1 / 60 : ℝ) * h.mesh_n2_p1 + (-1 / 4 : ℝ) * h_n + (5 / 4 : ℝ) * h_frame
  have h_cal : ω .cal = ω .b * (-1 / 76) := by
    linear_combination (1 / 60 : ℝ) * h.mesh_p2_cal1 + (-1 / 5 : ℝ) * h_p + (6 / 5 : ℝ) * h_frame
  have h_spB : ω .spB = ω .b * (111 / 62) := by
    linear_combination (1 / 62 : ℝ) * h.mesh_fx49_nd62 + (-49 / 62 : ℝ) * h_frame + (111 / 62 : ℝ) * h_b
  have h_t_nodes : ω .t_nodes = ω .b * (-5 / 93) := by
    linear_combination (1 / 48 : ℝ) * h.mesh_nd64_nd48 + (-4 / 3 : ℝ) * h_spB + (7 / 3 : ℝ) * h_b
  have h_spC : ω .spC = ω .b * (95 / 44) := by
    linear_combination (1 / 44 : ℝ) * h.mesh_fx51_vn44 + (-51 / 44 : ℝ) * h_frame + (95 / 44 : ℝ) * h_b
  have h_x_vn26 : ω .x_vn26 = ω .b * (-295 / 572) := by
    linear_combination (1 / 26 : ℝ) * h.mesh_vn34_vn26 + (-17 / 13 : ℝ) * h_spC + (30 / 13 : ℝ) * h_b
  have h_x_r1 : ω .x_r1 = ω .b * (751 / 462) := by
    linear_combination (1 / 63 : ℝ) * h.mesh_vn26_r1 + (-26 / 63 : ℝ) * h_x_vn26 + (89 / 63 : ℝ) * h_b
  have h_spA : ω .spA = ω .b * (41 / 24) := by
    linear_combination (1 / 72 : ℝ) * h.mesh_fx51_me72 + (-17 / 24 : ℝ) * h_frame + (41 / 24 : ℝ) * h_b
  have h_x_me40 : ω .x_me40 = ω .b * (-553 / 960) := by
    linear_combination (1 / 40 : ℝ) * h.mesh_me89_me40 + (-89 / 40 : ℝ) * h_spA + (129 / 40 : ℝ) * h_b
  have h_x_me20 : ω .x_me20 = ω .b * (1993 / 480) := by
    linear_combination (1 / 20 : ℝ) * h.mesh_me40_me20 + (-2 : ℝ) * h_x_me40 + (3 : ℝ) * h_b
  have h_x_cp52 : ω .x_cp52 = ω .b * (27 / 13) := by
    linear_combination (1 / 52 : ℝ) * h.mesh_fx56_cp52 + (-14 / 13 : ℝ) * h_frame + (27 / 13 : ℝ) * h_b
  have h_x_su56 : ω .x_su56 = ω .b * (0) := by
    linear_combination (1 / 56 : ℝ) * h.mesh_cp52_su56 + (-13 / 14 : ℝ) * h_x_cp52 + (27 / 14 : ℝ) * h_b
  have h_x_cp64 : ω .x_cp64 = ω .b * (15 / 8) := by
    linear_combination (1 / 64 : ℝ) * h.mesh_fx56_cp64 + (-7 / 8 : ℝ) * h_frame + (15 / 8 : ℝ) * h_b
  have h_x_sa40 : ω .x_sa40 = ω .b * (-167 / 260) := by
    linear_combination (1 / 40 : ℝ) * h.mesh_sa61_sa40 + (-61 / 40 : ℝ) * h_x_cp52 + (101 / 40 : ℝ) * h_b
  have h_x_sa68 : ω .x_sa68 = ω .b * (869 / 442) := by
    linear_combination (1 / 68 : ℝ) * h.mesh_sa40_sa68 + (-10 / 17 : ℝ) * h_x_sa40 + (27 / 17 : ℝ) * h_b
  have h_x_ju40 : ω .x_ju40 = ω .b * (1 / 64) := by
    linear_combination (1 / 40 : ℝ) * h.mesh_ju45_ju40 + (-9 / 8 : ℝ) * h_x_cp64 + (17 / 8 : ℝ) * h_b
  have h_x_ju43 : ω .x_ju43 = ω .b * (659 / 344) := by
    linear_combination (1 / 43 : ℝ) * h.mesh_ju40_ju43 + (-40 / 43 : ℝ) * h_x_ju40 + (83 / 43 : ℝ) * h_b
  have h_x_ma40 : ω .x_ma40 = ω .b * (27 / 160) := by
    linear_combination (1 / 40 : ℝ) * h.mesh_ma38_ma40 + (-19 / 20 : ℝ) * h_x_cp64 + (39 / 20 : ℝ) * h_b
  have h_x_ma71 : ω .x_ma71 = ω .b * (417 / 284) := by
    linear_combination (1 / 71 : ℝ) * h.mesh_ma40_ma71 + (-40 / 71 : ℝ) * h_x_ma40 + (111 / 71 : ℝ) * h_b
  have h_a : ω .a = ω .b * (223 / 48) := by
    linear_combination (1 / 48 : ℝ) * h.crown_a1_b1 + (223 / 48 : ℝ) * h_b
  have h_kp : ω .kp = ω .b * (55688 / 4237) := by
    linear_combination (1 : ℝ) * h.pinslot_lunar + (1 : ℝ) * h_k
  have h_e_inner : ω .e_inner = ω .b * (-254 / 19) := by
    linear_combination (1 / 50 : ℝ) * h.mesh_k2_e6 + (-1 : ℝ) * h_kp + (2 : ℝ) * h_e_table
  have h_moon : ω .moon = ω .b * (254 / 19) := by
    linear_combination (1 / 32 : ℝ) * h.mesh_e1_b3 + (-1 : ℝ) * h_e_inner + (2 : ℝ) * h_frame
  have h_q : ω .q = ω .b * (235 / 19) := by
    linear_combination (1 / 20 : ℝ) * h.crown_b0_q1 + (1 : ℝ) * h_moon + (-1 : ℝ) * h_b
  have h_x_sa86s : ω .x_sa86s = ω .b * (869 / 442) := by
    linear_combination (1 : ℝ) * h.pinslot_saturn + (1 : ℝ) * h_x_sa68
  have h_t_saturn : ω .t_saturn = ω .b * (15 / 442) := by
    linear_combination (1 / 86 : ℝ) * h.mesh_sa86s_sa86o + (-1 : ℝ) * h_x_sa86s + (2 : ℝ) * h_b
  have h_x_ju65s : ω .x_ju65s = ω .b * (659 / 344) := by
    linear_combination (1 : ℝ) * h.pinslot_jupiter + (1 : ℝ) * h_x_ju43
  have h_t_jupiter : ω .t_jupiter = ω .b * (29 / 344) := by
    linear_combination (1 / 65 : ℝ) * h.mesh_ju65s_ju65o + (-1 : ℝ) * h_x_ju65s + (2 : ℝ) * h_b
  have h_x_ma80s : ω .x_ma80s = ω .b * (417 / 284) := by
    linear_combination (1 : ℝ) * h.pinslot_mars + (1 : ℝ) * h_x_ma71
  have h_t_mars : ω .t_mars = ω .b * (151 / 284) := by
    linear_combination (1 / 80 : ℝ) * h.mesh_ma80s_ma80o + (-1 : ℝ) * h_x_ma80s + (2 : ℝ) * h_b
  have h_t_mercury : ω .t_mercury = ω .b * (1) := by
    linear_combination (1 : ℝ) * h.follower_mercury + (1 : ℝ) * h_b
  have h_t_venus : ω .t_venus = ω .b * (1) := by
    linear_combination (1 : ℝ) * h.follower_venus + (1 : ℝ) * h_b
  have h_t_trueSun : ω .t_trueSun = ω .b * (1) := by
    linear_combination (1 : ℝ) * h.follower_trueSun + (1 : ℝ) * h_b
  intro x
  cases x
  · exact h_frame
  · exact h_a
  · exact h_b
  · exact h_moon
  · exact h_c
  · exact h_d
  · exact h_e_pipe
  · exact h_e_table
  · exact h_e_inner
  · exact h_k
  · exact h_kp
  · exact h_l
  · exact h_m
  · exact h_f
  · exact h_g
  · exact h_h
  · exact h_i
  · exact h_n
  · exact h_o
  · exact h_p
  · exact h_cal
  · exact h_q
  · exact h_spA
  · exact h_spB
  · exact h_spC
  · exact h_x_me40
  · exact h_x_me20
  · exact h_x_vn26
  · exact h_x_r1
  · exact h_t_nodes
  · exact h_x_cp52
  · exact h_x_cp64
  · exact h_x_su56
  · exact h_x_sa40
  · exact h_x_sa68
  · exact h_x_sa86s
  · exact h_x_ju40
  · exact h_x_ju43
  · exact h_x_ju65s
  · exact h_x_ma40
  · exact h_x_ma71
  · exact h_x_ma80s
  · exact h_t_saturn
  · exact h_t_jupiter
  · exact h_t_mars
  · exact h_t_mercury
  · exact h_t_venus
  · exact h_t_trueSun

/-- **The mechanism can move**: there are admissible rates with b1 turning once a year, so the
hypotheses `Kinematics ω` and `ω .b = 1` used by the target theorems are not contradictory. -/
theorem moves : ∃ ω : Body → ℝ, Kinematics ω ∧ ω .b = 1 :=
  ⟨fun x => 1 * rate x, consistent 1, by simp [rate]⟩

/-- **The crank drives everything**: every mean rate is fixed by the crank's rate. -/
theorem determined_by_crank (ω : Body → ℝ) (h : Kinematics ω) :
    ∀ x, ω x = ω .a * (48 / 223) * rate x := by
  intro x
  rw [determined ω h x, determined ω h .a]
  simp only [rate]
  ring

/-- **One degree of freedom**: the set of admissible mean-rate vectors is exactly the line
`{t • rate}` (a line, not a point, since `rate .b = 1`). -/
theorem one_dof : {ω : Body → ℝ | Kinematics ω} = Set.range (fun t : ℝ => fun x => t * rate x) := by
  ext ω
  constructor
  · intro h
    exact ⟨ω .b, funext fun x => (determined ω h x).symm⟩
  · rintro ⟨t, rfl⟩
    exact consistent t

end Antikythera
