-- GENERATED by tools/make_lean.py from spec/antikythera.json. Do not edit by hand.

import Antikythera.Kinematics

/-!
# The astronomical targets of the spec, derived from the tooth counts alone

Each theorem assumes only `Kinematics ω` (the gear contacts) and b1 = 1 turn per year; `moves` shows
that these hypotheses are satisfiable. `target_b` is the normalisation itself; the others are derived
from the tooth counts. -/

namespace Antikythera

/-- crank: crank turns per year (magnitude) [definition]. Signed, under spec `conventions.crank`. -/
theorem target_a (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .a = 223 / 48 := by
  rw [determined ω h .a, hb]
  norm_num [rate]

/-- mean Sun: tropical year [F21]. This is the normalisation (b1 = 1 turn per year), not a derived result. -/
theorem target_b (ω : Body → ℝ) (_h : Kinematics ω) (hb : ω .b = 1) :
    ω .b = 1 := by
  exact hb

/-- Moon (mean sidereal): 254 sidereal months in 19 years [F06]. -/
theorem target_moon (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .moon = 254 / 19 := by
  rw [determined ω h .moon, hb]
  norm_num [rate]

/-- lunar apsidal line: 8.8826 yr [F06]. -/
theorem target_e_table (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .e_table = -477 / 4237 := by
  rw [determined ω h .e_table, hb]
  norm_num [rate]

/-- lunar anomaly phase (k1 relative to e3): anomalistic month [F06]. -/
theorem target_k_rel_e_table (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .k - ω .e_table = 56165 / 4237 := by
  rw [determined ω h .k, determined ω h .e_table, hb]
  norm_num [rate]

/-- Moon phase (q1 relative to Moon pointer, magnitude): synodic month [F06/F21]. `ω .q` is already relative to the Moon pointer; signed, under `conventions.moon_phase`. -/
theorem target_q_rel_moon (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .q = 235 / 19 := by
  rw [determined ω h .q, hb]
  norm_num [rate]

/-- Metonic pointer: 5 turns = 19 years = 235 synodic months [F06]. -/
theorem target_n (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .n = -5 / 19 := by
  rw [determined ω h .n, hb]
  norm_num [rate]

/-- Olympiad pointer: 4-year games cycle [F08]. -/
theorem target_o (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .o = 1 / 4 := by
  rw [determined ω h .o, hb]
  norm_num [rate]

/-- Callippic pointer: 76 years [F08]. -/
theorem target_cal (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .cal = -1 / 76 := by
  rw [determined ω h .cal, hb]
  norm_num [rate]

/-- Saros pointer: 4 turns = 223 synodic months [F06]. -/
theorem target_g (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .g = -940 / 4237 := by
  rw [determined ω h .g, hb]
  norm_num [rate]

/-- Exeligmos pointer: 1 turn = 3 Saros [F06]. -/
theorem target_i (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .i = -235 / 12711 := by
  rw [determined ω h .i, hb]
  norm_num [rate]

/-- Dragon Hand (nodes): 18.6 years retrograde [F21 (hypothetical)]. -/
theorem target_t_nodes (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .t_nodes = -5 / 93 := by
  rw [determined ω h .t_nodes, hb]
  norm_num [rate]

/-- draconic month (Moon - nodes): draconic month [derived]. -/
theorem target_moon_t_nodes (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .moon - ω .t_nodes = 23717 / 1767 := by
  rw [determined ω h .moon, determined ω h .t_nodes, hb]
  norm_num [rate]

/-- Mercury epicycle relative to b1: 1513 synodic periods in 480 years [F21 (hypothetical)]. -/
theorem target_x_me20_rel_b (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .x_me20 - ω .b = 1513 / 480 := by
  rw [determined ω h .x_me20, hb]
  norm_num [rate]

/-- Venus epicycle relative to b1: 289 synodic periods in 462 years [F21 (hypothetical)]. -/
theorem target_x_r1_rel_b (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .x_r1 - ω .b = 289 / 462 := by
  rw [determined ω h .x_r1, hb]
  norm_num [rate]

/-- true-Sun epicycle absolute: translation only; follower mean +1 [F21 (hypothetical)]. -/
theorem target_x_su56 (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .x_su56 = 0 := by
  rw [determined ω h .x_su56, hb]
  norm_num [rate]

/-- Mars pin gear relative to CP: 133 synodic periods in 284 years; output 151/284 [F21 (hypothetical)]. -/
theorem target_x_ma71_rel_b (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .x_ma71 - ω .b = 133 / 284 := by
  rw [determined ω h .x_ma71, hb]
  norm_num [rate]

/-- Jupiter pin gear relative to CP: 315 synodic periods in 344 years; output 29/344 [F21 (hypothetical)]. -/
theorem target_x_ju43_rel_b (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .x_ju43 - ω .b = 315 / 344 := by
  rw [determined ω h .x_ju43, hb]
  norm_num [rate]

/-- Saturn pin gear relative to CP: 427 synodic periods in 442 years; output 15/442 [F21 (hypothetical)]. -/
theorem target_x_sa68_rel_b (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .x_sa68 - ω .b = 427 / 442 := by
  rw [determined ω h .x_sa68, hb]
  norm_num [rate]

/-- Mars output: sidereal 1.8808 yr [F21 (hypothetical)]. -/
theorem target_t_mars (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .t_mars = 151 / 284 := by
  rw [determined ω h .t_mars, hb]
  norm_num [rate]

/-- Jupiter output: sidereal 11.862 yr [F21 (hypothetical)]. -/
theorem target_t_jupiter (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .t_jupiter = 29 / 344 := by
  rw [determined ω h .t_jupiter, hb]
  norm_num [rate]

/-- Saturn output: sidereal 29.467 yr [F21 (hypothetical)]. -/
theorem target_t_saturn (ω : Body → ℝ) (h : Kinematics ω) (hb : ω .b = 1) :
    ω .t_saturn = 15 / 442 := by
  rw [determined ω h .t_saturn, hb]
  norm_num [rate]

end Antikythera
