"""Generate the Lean 4 formalisation of the gearing from spec/antikythera.json (reads ONLY the JSON).

Writes lean/Antikythera/{Kinematics,Targets,Geometry}.lean. Lean's kernel then checks:
  * Kinematics: every body's mean rate is DETERMINED by the crank (proof by explicit linear combinations of the
    Willis / pin-and-slot / follower / crown constraints), the equations are CONSISTENT for every crank speed
    (no over-constrained loop, and the mechanism can move: the hypotheses of the other theorems are satisfiable
    with b1 turning), hence the mean-rate vector has exactly ONE degree of freedom;
  * Targets: each of the spec's astronomical targets follows from the tooth counts alone;
  * Geometry: every external mesh sits at its theoretical centre distance m(z1+z2)/2, to within 1e-6 mm.
Rates are recomputed here with exact fractions (independently of the spec's declared rates, which are only
cross-checked), and every number that reaches Lean is re-proved there: nothing is taken on trust.
"""
import argparse, json, re
from fractions import Fraction as F
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ap = argparse.ArgumentParser()
ap.add_argument('--spec', type=Path, default=ROOT / 'spec' / 'antikythera.json')
ap.add_argument('--out', type=Path, default=ROOT / 'lean' / 'Antikythera')
ap.add_argument('--skip-declared-check', action='store_true',
                help='do not compare with the spec\'s declared rates (used by tools/lean_mutation_test.py '
                     'to let Lean, not Python, reject a mutated spec)')
ARGS = ap.parse_args()
S = json.loads(ARGS.spec.read_text())
OUT = ARGS.out
OUT.mkdir(parents=True, exist_ok=True)
G = {g['id']: g for g in S['gears']}
BODIES = [b['id'] for b in S['bodies']]
BD = {b['id']: b for b in S['bodies']}
HEADER = "-- GENERATED by tools/make_lean.py from spec/antikythera.json. Do not edit by hand.\n"

def lit(q: F) -> str:
    """A Lean real literal for a fraction, e.g. -32 / 19, 0, 1."""
    q = F(q)
    return str(q.numerator) if q.denominator == 1 else f"{q.numerator} / {q.denominator}"

def coef(q: F) -> str:
    return f"({lit(q)} : ℝ)"

# ---------------- constraints: (field name, doc, {body: coefficient}) meaning  Σ coef·ω(body) = 0 ----------------
CONS = []
def add(name, doc, lhs_terms, lean_eq):
    d = {}
    for c, b in lhs_terms:
        d[b] = d.get(b, F(0)) + F(c)
    CONS.append(dict(name=name, doc=doc, terms={b: c for b, c in d.items() if c != 0}, eq=lean_eq))

add('frame_fixed', 'The frame (plates, fixed central tube, Sub-Plate gear) does not turn.',
    [(1, 'frame')], "ω .frame = 0")
for m in S['meshes']:
    g1, g2 = G[m['driver']], G[m['driven']]
    b1, b2, c = g1['body'], g2['body'], m['carrier']
    z1, z2 = g1['teeth'], g2['teeth']
    if m['type'] == 'external':
        add(f"mesh_{g1['id']}_{g2['id']}",
            f"{g1['id']} ({z1} teeth, on `{b1}`) meshes with {g2['id']} ({z2} teeth, on `{b2}`); axes carried by "
            f"`{c}`. Willis: z₁(ω₁ − ω_c) + z₂(ω₂ − ω_c) = 0.",
            [(z1, b1), (-z1, c), (z2, b2), (-z2, c)],
            f"{z1} * (ω .{b1} - ω .{c}) + {z2} * (ω .{b2} - ω .{c}) = 0")
    elif (g1['id'], g2['id']) == ('a1', 'b1'):
        assert m['carrier'] == 'frame' and BD['a']['axis'].lstrip('+') == 'x', "crank crown geometry changed"
        add('crown_a1_b1',
            f"Crown (contrate) pair a1 ({z1}) → b1 ({z2}) on perpendicular axes: the crank `a` turns {z2}/{z1} times "
            "per turn of b1 (sense of `a` counted positive when it drives b1 clockwise).",
            [(z1, 'a'), (-z2, 'b')], f"{z1} * ω .a = {z2} * ω .b")
    elif (g1['id'], g2['id']) == ('b0', 'q1'):
        assert m['carrier'] == 'moon' and BD['q']['parent'] == 'moon', "moon-phase crown geometry changed"
        add('crown_b0_q1',
            f"Crown pair b0 ({z1}, on `b`) → q1 ({z2}, the Moon-phase ball `q`) on the Moon pointer. `ω .q` is the "
            "ball's rate RELATIVE TO THE MOON POINTER about its radial axis, right-handed (spec "
            "`conventions.moon_phase`: θ_q = θ_b − θ_moon in counterclockwise world angles, i.e. "
            "ω_q = ω_moon − ω_b in the clockwise-positive rates used here): one turn per synodic month.",
            [(z2, 'q'), (-z1, 'moon'), (z1, 'b')], f"{z2} * ω .q = {z1} * (ω .moon - ω .b)")
    else:
        raise SystemExit(f"unhandled mesh {m}")
for ps in S['pin_slots']:
    pb, sb = G[ps['pin_gear']]['body'], G[ps['slot_gear']]['body']
    add(f"pinslot_{ps['id']}",
        f"Pin-and-slot `{ps['id']}` ({ps['pin_gear']} → {ps['slot_gear']}, pin radius {ps['pin_radius']} mm, offset "
        f"{ps['offset']} mm): the slot gear's MEAN rate equals the pin gear's (the angular lag is bounded, see "
        "`Antikythera.PinSlot.kinematics_nonlinear_fields`, which derives this equation from the spec's "
        "nonlinear law).",
        [(1, sb), (-1, pb)], f"ω .{sb} = ω .{pb}")
for fo in S['followers']:
    add(f"follower_{fo['id']}",
        f"Follower `{fo['id']}` (pin on `{fo['epicycle_body']}`, i = {fo['i']}, d = {fo['pin_d']}): its MEAN rate is "
        "the Sun's (the lag is bounded because d < i, see "
        "`Antikythera.PinSlot.kinematics_nonlinear_fields`).",
        [(1, fo['body']), (-1, 'b')], f"ω .{fo['body']} = ω .b")

# ---------------- exact propagation from b (= 1 turn/year) ----------------
rate = {'b': F(1)}
steps = [('b', None)]
pending = list(CONS)
while pending:
    for c in pending:
        unk = [b for b in c['terms'] if b not in rate]
        if len(unk) == 1:
            u = unk[0]; au = c['terms'][u]
            rate[u] = -sum(a * rate[b] for b, a in c['terms'].items() if b != u) / au
            steps.append((u, c)); pending.remove(c); break
        if not unk:
            if sum(a * rate[b] for b, a in c['terms'].items()) != 0:
                raise SystemExit(f"inconsistent constraint {c['name']}")
            steps.append((None, c)); pending.remove(c); break
    else:
        raise SystemExit(f"cannot determine: {[c['name'] for c in pending]}")
missing = [b for b in BODIES if b not in rate]
if missing: raise SystemExit(f"undetermined bodies {missing}")
if not ARGS.skip_declared_check:
    for b in BODIES:
        decl = BD[b]['rate_abs_mean']
        if decl is not None and F(decl) != rate[b]:
            raise SystemExit(f"declared rate of {b} = {decl} but the gearing gives {rate[b]}")
if rate['a'] != F(223, 48) or rate['q'] != F(235, 19) or rate['b'] != 1:
    raise SystemExit(f"crown rates {rate['a']} {rate['q']}")
n_redundant = sum(1 for u, c in steps if u is None and c is not None)

# ---------------- Kinematics.lean ----------------
L = [HEADER, "import Mathlib\n",
     "/-!\n# The Antikythera Mechanism: kinematics of the gearing\n",
     "Every moving part is a `Body`. `ω x` is the MEAN rate of body `x` in turns per year about its own axis,",
     "positive = clockwise seen from the front (spec `conventions.rate_sign`); `b` is the main wheel b1",
     "(1 turn = 1 year). Two exceptions, both on perpendicular axes: `ω .a` is the crank's rate about the x axis,",
     "counted positive when it drives b1 clockwise (spec `conventions.crank`), and `ω .q` is the Moon-phase",
     "ball's rate RELATIVE TO THE MOON POINTER about its radial axis (spec `conventions.moon_phase`).",
     "`Kinematics ω` collects one equation per gear contact, taken from the tooth counts of the spec.\n",
     "Main results: `determined` and `determined_by_crank` (the crank fixes every mean rate), `consistent`",
     "(the equations admit a solution for every crank speed: no over-constrained loop), `moves` (the",
     "mechanism can turn: the hypotheses used elsewhere are satisfiable with b1 turning) and `one_dof` (the",
     "admissible mean-rate vectors form exactly one line: one degree of freedom). These are statements about",
     "MEAN rates; the nonlinear pin-and-slot and follower laws are treated in `Antikythera.PinSlot`, and",
     "geometric interference (collisions) is outside the scope of the Lean proofs.\n-/\n",
     "namespace Antikythera\n",
     "/-- The rigid bodies of the mechanism (spec `bodies`). -/",
     "inductive Body where"]
for b in BODIES:
    extra = {'a': ' (rate about the x axis)', 'q': ' (rate relative to the Moon pointer, radial axis)'}.get(b, '')
    L.append(f"  | {b} -- {BD[b]['kind']}; gears {', '.join(BD[b]['gears']) or '—'}{extra}")
L.append("  deriving DecidableEq, Repr\n")
L += ["/-- The gear-contact constraints on the mean rates `ω`. -/",
      "structure Kinematics (ω : Body → ℝ) : Prop where"]
for c in CONS:
    L.append(f"  /-- {c['doc']} -/")
    L.append(f"  {c['name']} : {c['eq']}")
L.append("")
L += ["/-- The mean rates for b1 = 1 turn per year, computed exactly from the tooth counts. -/",
      "noncomputable def rate : Body → ℝ"]
for b in BODIES:
    L.append(f"  | .{b} => {lit(rate[b])}")
L.append("")
L += ["/-- **Consistency**: for every crank speed `t` the rates `t • rate` satisfy all constraints: the",
      f"{len(CONS)} equations are independent ({len(BODIES)} bodies, no over-constrained loop). -/",
      "theorem consistent (t : ℝ) : Kinematics (fun x => t * rate x) := by",
      "  constructor <;> simp only [rate] <;> ring\n"]
L += ["/-- **Determinism**: any rates satisfying the constraints are fixed by the rate of b1. -/",
      "theorem determined (ω : Body → ℝ) (h : Kinematics ω) : ∀ x, ω x = ω .b * rate x := by"]
hname = lambda b: f"h_{b}"
for u, c in steps:
    if c is None:
        L.append(f"  have {hname('b')} : ω .b = ω .b * 1 := by ring")
        continue
    if u is None:
        continue
    au = c['terms'][u]
    parts = [f"{coef(1 / au)} * h.{c['name']}"]
    for b, a in c['terms'].items():
        if b != u:
            parts.append(f"{coef(-a / au)} * {hname(b)}")
    L.append(f"  have {hname(u)} : ω .{u} = ω .b * ({lit(rate[u])}) := by")
    L.append(f"    linear_combination {' + '.join(parts)}")
L.append("  intro x")
L.append("  cases x")
for b in BODIES:
    L.append(f"  · exact {hname(b)}")
L.append("")
L += ["/-- **The mechanism can move**: there are admissible rates with b1 turning once a year, so the",
      "hypotheses `Kinematics ω` and `ω .b = 1` used by the target theorems are not contradictory. -/",
      "theorem moves : ∃ ω : Body → ℝ, Kinematics ω ∧ ω .b = 1 :=",
      "  ⟨fun x => 1 * rate x, consistent 1, by simp [rate]⟩\n",
      "/-- **The crank drives everything**: every mean rate is fixed by the crank's rate. -/",
      "theorem determined_by_crank (ω : Body → ℝ) (h : Kinematics ω) :",
      "    ∀ x, ω x = ω .a * (48 / 223) * rate x := by",
      "  intro x",
      "  rw [determined ω h x, determined ω h .a]",
      "  simp only [rate]",
      "  ring\n",
      "/-- **One degree of freedom**: the set of admissible mean-rate vectors is exactly the line",
      "`{t • rate}` (a line, not a point, since `rate .b = 1`). -/",
      "theorem one_dof : {ω : Body → ℝ | Kinematics ω} = Set.range (fun t : ℝ => fun x => t * rate x) := by",
      "  ext ω",
      "  constructor",
      "  · intro h",
      "    exact ⟨ω .b, funext fun x => (determined ω h x).symm⟩",
      "  · rintro ⟨t, rfl⟩",
      "    exact consistent t\n",
      "end Antikythera\n"]
(OUT / 'Kinematics.lean').write_text('\n'.join(L))

# ---------------- Targets.lean ----------------
def expr_lean(e):
    """(lean expression, bodies used)"""
    if e == 'q@moon': return "ω .q", ['q']
    if e == 'moon-t_nodes': return "ω .moon - ω .t_nodes", ['moon', 't_nodes']
    if '@' in e:
        x, c = e.split('@'); return f"ω .{x} - ω .{c}", [x, c]
    return f"ω .{e}", [e]
T = [HEADER, "import Antikythera.Kinematics\n",
     "/-!\n# The astronomical targets of the spec, derived from the tooth counts alone\n",
     "Each theorem assumes only `Kinematics ω` (the gear contacts) and b1 = 1 turn per year; `moves` shows",
     "that these hypotheses are satisfiable. `target_b` is the normalisation itself; the others are derived",
     "from the tooth counts. -/\n",
     "namespace Antikythera\n"]
seen = set()
for t in S['targets']:
    ex, used = expr_lean(t['expr'])
    nm = 'target_' + re.sub(r'[^A-Za-z0-9]+', '_', t['expr'].replace('@', '_rel_')).strip('_')
    assert nm not in seen; seen.add(nm)
    val = F(t['value'])
    rw = ', '.join(f"determined ω h .{b}" for b in used if b != 'b')
    note = {'b': ' This is the normalisation (b1 = 1 turn per year), not a derived result.',
            'a': ' Signed, under spec `conventions.crank`.',
            'q@moon': ' `ω .q` is already relative to the Moon pointer; signed, under `conventions.moon_phase`.'}.get(t['expr'], '')
    T.append(f"/-- {t['name']}: {t['cycle']} [{t['source']}].{note} -/")
    hk = '_h' if used == ['b'] else 'h'
    T.append(f"theorem {nm} (ω : Body → ℝ) ({hk} : Kinematics ω) (hb : ω .b = 1) :")
    T.append(f"    {ex} = {lit(val)} := by")
    if used == ['b']:
        T.append("  exact hb\n")
    else:
        T.append(f"  rw [{rw}, hb]")
        T.append("  norm_num [rate]\n")
T.append("end Antikythera\n")
(OUT / 'Targets.lean').write_text('\n'.join(T))

# ---------------- Geometry.lean ----------------
E = S['axes_world_xy']['E']
def axis(g):
    b = BD[G[g]['body']]
    if b['parent'] == 'e_table':
        return tuple(f"({v!r})" for v in (E[0], E[1], *b['axis_xy_in_parent']))
    xy = b['axis_xy_in_parent'] or [0.0, 0.0]
    return tuple(f"({v!r})" for v in xy)
def xy(g):
    a = axis(g)
    return (f"({a[0]} + {a[2]})", f"({a[1]} + {a[3]})") if len(a) == 4 else a
Gm = [HEADER, "import Mathlib\n",
      "/-!\n# Centre distances\n",
      "For every external mesh, the two gears have the same module and the distance between their axes equals",
      "the theoretical centre distance m(z₁ + z₂)/2 to within 10⁻⁶ mm. Coordinates are the spec's axis positions",
      "in mm, in world coordinates at crank = 0 (the b1 frame coincides with the world frame there; axes on the",
      "e3 turntable are written as E + local offset). Distances within one carrier do not depend on the crank.",
      "Contact ratio, face overlap, undercut and collisions are checked by the Python tools, not here. -/\n",
      "namespace Antikythera.Geometry\n"]
cnt = 0
for m in S['meshes']:
    if m['type'] != 'external': continue
    g1, g2 = G[m['driver']], G[m['driven']]
    (x1, y1), (x2, y2) = xy(g1['id']), xy(g2['id'])
    a = f"({repr(g1['module'])} * ({g1['teeth']} + {g2['teeth']}) / 2 : ℝ)"
    d2 = f"({x1} - {x2} : ℝ) ^ 2 + ({y1} - {y2} : ℝ) ^ 2"
    Gm.append(f"/-- {g1['id']} ({g1['teeth']}) ~ {g2['id']} ({g2['teeth']}), module {g1['module']}. -/")
    Gm.append(f"theorem centre_{g1['id']}_{g2['id']} :")
    Gm.append(f"    ({repr(g1['module'])} : ℝ) = {repr(g2['module'])} ∧")
    Gm.append(f"    ({a} - 1e-6) ^ 2 < {d2} ∧")
    Gm.append(f"    {d2} < ({a} + 1e-6) ^ 2 := by")
    Gm.append("  refine ⟨?_, ?_, ?_⟩ <;> norm_num\n")
    cnt += 1
Gm.append("end Antikythera.Geometry\n")
(OUT / 'Geometry.lean').write_text('\n'.join(Gm))

print(f"bodies {len(BODIES)}, constraints {len(CONS)}, redundant {n_redundant}, targets {len(S['targets'])}, "
      f"centre distances {cnt}")
